import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_compnents/Navbar";
import Footer from "./_compnents/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer/>  
      </body>
    </html>
  );
}
